// This code is generated by generate_code.py, do not modify it manually.

//! This module contains all the known columns in the skymapperdr2_neighbourhood table.

use crate::traits::{Column, Table};

/// The skymapperdr2_neighbourhood table.
#[allow(non_camel_case_types)]
pub struct skymapperdr2_neighbourhood;

impl Table for skymapperdr2_neighbourhood {
    fn string(&self) -> String {
        "skymapperdr2_neighbourhood".to_string()
    }
}

/// The columns in the skymapperdr2_neighbourhood table.
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, strum::Display)]
pub enum Col {
    source_id,
    original_ext_source_id,
    angular_distance,
    score,
    xm_flag,
}

impl Column for Col {}

#[cfg(test)]
pub fn collect_known(map: &mut std::collections::HashMap<String, Vec<String>>) {
    let mut col_strings = Vec::new();
    col_strings.push(Col::source_id.to_string());
    col_strings.push(Col::original_ext_source_id.to_string());
    col_strings.push(Col::angular_distance.to_string());
    col_strings.push(Col::score.to_string());
    col_strings.push(Col::xm_flag.to_string());
    map.insert(skymapperdr2_neighbourhood.string(), col_strings);
}
