// This code is generated by generate_code.py, do not modify it manually.

//! This module contains all the known columns in the vari_eclipsing_binary table.

use crate::traits::{Column, Table};

/// This table describes the properties of the eclipsing binaries resulting from the variability analysis.
#[allow(non_camel_case_types)]
pub struct vari_eclipsing_binary;

impl Table for vari_eclipsing_binary {
    fn string(&self) -> String {
        "vari_eclipsing_binary".to_string()
    }
}

/// The columns in the vari_eclipsing_binary table.
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, strum::Display)]
pub enum Col {
    /// Solution Identifier
    solution_id,
    /// Unique source identifier
    source_id,
    /// Number between 0 (worst) and 1 (best)
    global_ranking,
    /// Reference time used for the geometric model fit
    reference_time,
    /// Frequency of geometric model of the eclipsing binary light curve
    frequency,
    /// Uncertainty of \texttt{frequency}
    frequency_error,
    /// Magnitude reference level of geometric model
    geom_model_reference_level,
    /// Uncertainty of \texttt{geomModelReferenceLevel}
    geom_model_reference_level_error,
    /// Phase of the Gaussian 1 component
    geom_model_gaussian1_phase,
    /// Uncertainty of \texttt{geomModelGaussian1Phase}
    geom_model_gaussian1_phase_error,
    /// Standard deviation [phase] of Gaussian 1 component
    geom_model_gaussian1_sigma,
    /// Uncertainty of \texttt{geomModelGaussian1Sigma}
    geom_model_gaussian1_sigma_error,
    /// Magnitude depth of Gaussian 1 component
    geom_model_gaussian1_depth,
    /// Uncertainty of \texttt{geomModelGaussian1Depth}
    geom_model_gaussian1_depth_error,
    /// Phase of Gaussian 2 component
    geom_model_gaussian2_phase,
    /// Uncertainty of \texttt{geomModelGaussian2Phase}
    geom_model_gaussian2_phase_error,
    /// Standard deviation [phase] of Gaussian 2 component
    geom_model_gaussian2_sigma,
    /// Uncertainty of \texttt{geomModelGaussian2Sigma}
    geom_model_gaussian2_sigma_error,
    /// Magnitude depth of Gaussian2 component
    geom_model_gaussian2_depth,
    /// Uncertainty of \texttt{geomModelGaussian2Depth}
    geom_model_gaussian2_depth_error,
    /// Amplitude of the cosine component with half the period of the geometric model
    geom_model_cosine_half_period_amplitude,
    /// Uncertainty of \texttt{geomModelCosineHalfPeriodAmplitude}
    geom_model_cosine_half_period_amplitude_error,
    /// Reference phase of the cosine component with half the period of the geometric model
    geom_model_cosine_half_period_phase,
    /// Uncertainty of \texttt{geomModelCosineHalfPeriodPhase}
    geom_model_cosine_half_period_phase_error,
    /// Type of geometrical model of the light curve
    model_type,
    /// Number of free parameters of the geometric model
    num_model_parameters,
    /// Reduced Chi2 of the geometrical model fit
    reduced_chi2,
    /// Primary eclipse: phase at geometrically deepest point
    derived_primary_ecl_phase,
    /// Primary eclipse: uncertainty of \texttt{derivedPrimaryEclPhase}
    derived_primary_ecl_phase_error,
    /// Primary eclipse: duration [phase fraction]
    derived_primary_ecl_duration,
    /// Primary eclipse: uncertainty of \texttt{derivedPrimaryEclDuration}
    derived_primary_ecl_duration_error,
    /// Primary eclipse: depth
    derived_primary_ecl_depth,
    /// Primary eclipse: uncertainty of \texttt{derivedPrimaryEclDepth}
    derived_primary_ecl_depth_error,
    /// Secondary eclipse: phase at geometrically second deepest point
    derived_secondary_ecl_phase,
    /// Secondary eclipse: uncertainty of \texttt{derivedSecondaryEclPhase}
    derived_secondary_ecl_phase_error,
    /// Secondary eclipse: duration [phase fraction]
    derived_secondary_ecl_duration,
    /// Secondary eclipse: uncertainty of \texttt{derivedSecondaryEclDuration}
    derived_secondary_ecl_duration_error,
    /// Secondary eclipse: depth
    derived_secondary_ecl_depth,
    /// Secondary eclipse: uncertainty of \texttt{derivedSecondaryEclDepth}
    derived_secondary_ecl_depth_error,
}

impl Column for Col {}

#[cfg(test)]
pub fn collect_known(map: &mut std::collections::HashMap<String, Vec<String>>) {
    let mut col_strings = Vec::new();
    col_strings.push(Col::solution_id.to_string());
    col_strings.push(Col::source_id.to_string());
    col_strings.push(Col::global_ranking.to_string());
    col_strings.push(Col::reference_time.to_string());
    col_strings.push(Col::frequency.to_string());
    col_strings.push(Col::frequency_error.to_string());
    col_strings.push(Col::geom_model_reference_level.to_string());
    col_strings.push(Col::geom_model_reference_level_error.to_string());
    col_strings.push(Col::geom_model_gaussian1_phase.to_string());
    col_strings.push(Col::geom_model_gaussian1_phase_error.to_string());
    col_strings.push(Col::geom_model_gaussian1_sigma.to_string());
    col_strings.push(Col::geom_model_gaussian1_sigma_error.to_string());
    col_strings.push(Col::geom_model_gaussian1_depth.to_string());
    col_strings.push(Col::geom_model_gaussian1_depth_error.to_string());
    col_strings.push(Col::geom_model_gaussian2_phase.to_string());
    col_strings.push(Col::geom_model_gaussian2_phase_error.to_string());
    col_strings.push(Col::geom_model_gaussian2_sigma.to_string());
    col_strings.push(Col::geom_model_gaussian2_sigma_error.to_string());
    col_strings.push(Col::geom_model_gaussian2_depth.to_string());
    col_strings.push(Col::geom_model_gaussian2_depth_error.to_string());
    col_strings.push(Col::geom_model_cosine_half_period_amplitude.to_string());
    col_strings.push(Col::geom_model_cosine_half_period_amplitude_error.to_string());
    col_strings.push(Col::geom_model_cosine_half_period_phase.to_string());
    col_strings.push(Col::geom_model_cosine_half_period_phase_error.to_string());
    col_strings.push(Col::model_type.to_string());
    col_strings.push(Col::num_model_parameters.to_string());
    col_strings.push(Col::reduced_chi2.to_string());
    col_strings.push(Col::derived_primary_ecl_phase.to_string());
    col_strings.push(Col::derived_primary_ecl_phase_error.to_string());
    col_strings.push(Col::derived_primary_ecl_duration.to_string());
    col_strings.push(Col::derived_primary_ecl_duration_error.to_string());
    col_strings.push(Col::derived_primary_ecl_depth.to_string());
    col_strings.push(Col::derived_primary_ecl_depth_error.to_string());
    col_strings.push(Col::derived_secondary_ecl_phase.to_string());
    col_strings.push(Col::derived_secondary_ecl_phase_error.to_string());
    col_strings.push(Col::derived_secondary_ecl_duration.to_string());
    col_strings.push(Col::derived_secondary_ecl_duration_error.to_string());
    col_strings.push(Col::derived_secondary_ecl_depth.to_string());
    col_strings.push(Col::derived_secondary_ecl_depth_error.to_string());
    map.insert(vari_eclipsing_binary.string(), col_strings);
}
