// This code is generated by generate_code.py, do not modify it manually.

//! This module contains all the known columns in the crowded_field_source table.

use crate::traits::{Column, Table};

/// Sources based on Service Interface Function (SIF) images of very dense regions in the sky.
/// These sources build an add-on catalogue to the nominal Gaia catalogue.
/// Nominal and SIF detections were not mixed to create these sources.
/// These Sources are thus obtained from SIF image detections only.
/// Sources already present in the nominal catalogue were removed from the SIF add-on catalogue.
#[allow(non_camel_case_types)]
pub struct crowded_field_source;

impl Table for crowded_field_source {
    fn string(&self) -> String {
        "crowded_field_source".to_string()
    }
}

/// The columns in the crowded_field_source table.
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, strum::Display)]
pub enum Col {
    /// Solution Identifier
    solution_id,
    /// Unique source designation (unique across all Data Releases)
    designation,
    /// Name of the designated CrowdedField region in the sky
    region_name,
    /// Unique source identifier (unique within a particular Data Release) providing the CrowdedField-nature of the source via location bit
    source_id,
    /// Reference epoch
    ref_epoch,
    /// Right ascension
    ra,
    /// Standard error of right ascension
    ra_error,
    /// Declination
    dec,
    /// Standard error of declination
    dec_error,
    /// Parallax
    parallax,
    /// Standard error of parallax
    parallax_error,
    /// Parallax divided by its standard error
    parallax_over_error,
    /// Total proper motion
    pm,
    /// Proper motion in right ascension direction
    pmra,
    /// Standard error of proper motion in right ascension direction
    pmra_error,
    /// Proper motion in declination direction
    pmdec,
    /// Standard error of proper motion in declination direction
    pmdec_error,
    /// Correlation between right ascension and declination
    ra_dec_corr,
    /// Correlation between right ascension and parallax
    ra_parallax_corr,
    /// Correlation between right ascension and proper motion in right ascension
    ra_pmra_corr,
    /// Correlation between right ascension and proper motion in declination
    ra_pmdec_corr,
    /// Correlation between declination and parallax
    dec_parallax_corr,
    /// Correlation between declination and proper motion in right ascension
    dec_pmra_corr,
    /// Correlation between declination and proper motion in declination
    dec_pmdec_corr,
    /// Correlation between parallax and proper motion in right ascension
    parallax_pmra_corr,
    /// Correlation between parallax and proper motion in declination
    parallax_pmdec_corr,
    /// Correlation between proper motion in right ascension and proper motion in declination
    pmra_pmdec_corr,
    /// Number of CrowdedField scans of the source location
    n_scans,
    /// Total number of observations in the along-scan (AL) direction
    astrometric_n_obs_al,
    /// Total number of observations in the across-scan (AC) direction
    astrometric_n_obs_ac,
    /// Number of good observations in the along-scan (AL) direction
    astrometric_n_good_obs_al,
    /// Number of bad observations in the along-scan (AL) direction
    astrometric_n_bad_obs_al,
    /// Goodness of fit statistic of model wrt along-scan observations
    astrometric_gof_al,
    /// AL chi-square value
    astrometric_chi2_al,
    /// Excess noise of the source
    astrometric_excess_noise,
    /// Significance of excess noise
    astrometric_excess_noise_sig,
    /// Which parameters have been solved for?
    astrometric_params_solved,
    /// Astrometrically estimated pseudocolour of the source
    pseudocolour,
    /// Standard error of the pseudocolour of the source
    pseudocolour_error,
    /// Correlation between right ascension and pseudocolour
    ra_pseudocolour_corr,
    /// Correlation between declination and pseudocolour
    dec_pseudocolour_corr,
    /// Correlation between parallax and pseudocolour
    parallax_pseudocolour_corr,
    /// Correlation between proper motion in right asension and pseudocolour
    pmra_pseudocolour_corr,
    /// Correlation between proper motion in declination and pseudocolour
    pmdec_pseudocolour_corr,
    /// Matched FOV transits used in the AGIS solution
    astrometric_matched_transits,
    /// Number of visibility periods used in Astrometric solution
    visibility_periods_used,
    /// The longest semi-major axis of the 5-d error ellipsoid
    astrometric_sigma5d_max,
    /// The number of transits matched to this source
    matched_transits,
    /// Amplitude of the IPD GoF versus position angle of scan
    ipd_gof_harmonic_amplitude,
    /// Phase of the IPD GoF versus position angle of scan
    ipd_gof_harmonic_phase,
    /// Degree of concentration of scan directions across the source
    scan_direction_strength_k1,
    /// Degree of concentration of scan directions across the source
    scan_direction_strength_k2,
    /// Degree of concentration of scan directions across the source
    scan_direction_strength_k3,
    /// Degree of concentration of scan directions across the source
    scan_direction_strength_k4,
    /// Mean position angle of scan directions across the source
    scan_direction_mean_k1,
    /// Mean position angle of scan directions across the source
    scan_direction_mean_k2,
    /// Mean position angle of scan directions across the source
    scan_direction_mean_k3,
    /// Mean position angle of scan directions across the source
    scan_direction_mean_k4,
    /// Primary or secondary
    astrometric_primary_flag,
    /// Number of observations contributing to G photometry
    phot_g_n_obs,
    /// G-band mean flux
    phot_g_mean_flux,
    /// Error on G-band mean flux
    phot_g_mean_flux_error,
    /// G-band mean flux divided by its error
    phot_g_mean_flux_over_error,
    /// G-band mean magnitude
    phot_g_mean_mag,
    /// Unit weight variance of fluxes
    phot_g_flux_uwv,
    /// Median flux
    phot_g_flux_median,
    /// Measure of the skewness of the flux distribution
    phot_g_flux_skewness,
    /// Measure of the kurtosis of the flux distribution
    phot_g_flux_kurtosis,
    /// MAD of the flux distribution
    phot_g_flux_mad,
    /// First quartile of the flux distribution
    phot_g_flux_first_quartile,
    /// Third quartile of the flux distribution
    phot_g_flux_third_quartile,
    /// Minimum flux value
    phot_g_flux_min,
    /// Maximum flux value
    phot_g_flux_max,
    /// Photometry processing mode
    phot_proc_mode,
    /// Galactic longitude
    l,
    /// Galactic latitude
    b,
    /// Ecliptic longitude
    ecl_lon,
    /// Ecliptic latitude
    ecl_lat,
}

impl Column for Col {}

#[cfg(test)]
/// Collects all the known columns in the crowded_field_source table.
pub fn collect_known(map: &mut std::collections::HashMap<String, Vec<String>>) {
    let mut col_strings = Vec::new();
    col_strings.push(Col::solution_id.to_string());
    col_strings.push(Col::designation.to_string());
    col_strings.push(Col::region_name.to_string());
    col_strings.push(Col::source_id.to_string());
    col_strings.push(Col::ref_epoch.to_string());
    col_strings.push(Col::ra.to_string());
    col_strings.push(Col::ra_error.to_string());
    col_strings.push(Col::dec.to_string());
    col_strings.push(Col::dec_error.to_string());
    col_strings.push(Col::parallax.to_string());
    col_strings.push(Col::parallax_error.to_string());
    col_strings.push(Col::parallax_over_error.to_string());
    col_strings.push(Col::pm.to_string());
    col_strings.push(Col::pmra.to_string());
    col_strings.push(Col::pmra_error.to_string());
    col_strings.push(Col::pmdec.to_string());
    col_strings.push(Col::pmdec_error.to_string());
    col_strings.push(Col::ra_dec_corr.to_string());
    col_strings.push(Col::ra_parallax_corr.to_string());
    col_strings.push(Col::ra_pmra_corr.to_string());
    col_strings.push(Col::ra_pmdec_corr.to_string());
    col_strings.push(Col::dec_parallax_corr.to_string());
    col_strings.push(Col::dec_pmra_corr.to_string());
    col_strings.push(Col::dec_pmdec_corr.to_string());
    col_strings.push(Col::parallax_pmra_corr.to_string());
    col_strings.push(Col::parallax_pmdec_corr.to_string());
    col_strings.push(Col::pmra_pmdec_corr.to_string());
    col_strings.push(Col::n_scans.to_string());
    col_strings.push(Col::astrometric_n_obs_al.to_string());
    col_strings.push(Col::astrometric_n_obs_ac.to_string());
    col_strings.push(Col::astrometric_n_good_obs_al.to_string());
    col_strings.push(Col::astrometric_n_bad_obs_al.to_string());
    col_strings.push(Col::astrometric_gof_al.to_string());
    col_strings.push(Col::astrometric_chi2_al.to_string());
    col_strings.push(Col::astrometric_excess_noise.to_string());
    col_strings.push(Col::astrometric_excess_noise_sig.to_string());
    col_strings.push(Col::astrometric_params_solved.to_string());
    col_strings.push(Col::pseudocolour.to_string());
    col_strings.push(Col::pseudocolour_error.to_string());
    col_strings.push(Col::ra_pseudocolour_corr.to_string());
    col_strings.push(Col::dec_pseudocolour_corr.to_string());
    col_strings.push(Col::parallax_pseudocolour_corr.to_string());
    col_strings.push(Col::pmra_pseudocolour_corr.to_string());
    col_strings.push(Col::pmdec_pseudocolour_corr.to_string());
    col_strings.push(Col::astrometric_matched_transits.to_string());
    col_strings.push(Col::visibility_periods_used.to_string());
    col_strings.push(Col::astrometric_sigma5d_max.to_string());
    col_strings.push(Col::matched_transits.to_string());
    col_strings.push(Col::ipd_gof_harmonic_amplitude.to_string());
    col_strings.push(Col::ipd_gof_harmonic_phase.to_string());
    col_strings.push(Col::scan_direction_strength_k1.to_string());
    col_strings.push(Col::scan_direction_strength_k2.to_string());
    col_strings.push(Col::scan_direction_strength_k3.to_string());
    col_strings.push(Col::scan_direction_strength_k4.to_string());
    col_strings.push(Col::scan_direction_mean_k1.to_string());
    col_strings.push(Col::scan_direction_mean_k2.to_string());
    col_strings.push(Col::scan_direction_mean_k3.to_string());
    col_strings.push(Col::scan_direction_mean_k4.to_string());
    col_strings.push(Col::astrometric_primary_flag.to_string());
    col_strings.push(Col::phot_g_n_obs.to_string());
    col_strings.push(Col::phot_g_mean_flux.to_string());
    col_strings.push(Col::phot_g_mean_flux_error.to_string());
    col_strings.push(Col::phot_g_mean_flux_over_error.to_string());
    col_strings.push(Col::phot_g_mean_mag.to_string());
    col_strings.push(Col::phot_g_flux_uwv.to_string());
    col_strings.push(Col::phot_g_flux_median.to_string());
    col_strings.push(Col::phot_g_flux_skewness.to_string());
    col_strings.push(Col::phot_g_flux_kurtosis.to_string());
    col_strings.push(Col::phot_g_flux_mad.to_string());
    col_strings.push(Col::phot_g_flux_first_quartile.to_string());
    col_strings.push(Col::phot_g_flux_third_quartile.to_string());
    col_strings.push(Col::phot_g_flux_min.to_string());
    col_strings.push(Col::phot_g_flux_max.to_string());
    col_strings.push(Col::phot_proc_mode.to_string());
    col_strings.push(Col::l.to_string());
    col_strings.push(Col::b.to_string());
    col_strings.push(Col::ecl_lon.to_string());
    col_strings.push(Col::ecl_lat.to_string());
    map.insert(crowded_field_source.string(), col_strings);
}
