// This code is generated by generate_code.py, do not modify it manually
use crate::column::Column;
use crate::schema::Schema;

#[allow(non_camel_case_types)]
pub struct aux_iers_gdr2_cross_id;

impl Schema for aux_iers_gdr2_cross_id {
    fn string(&self) -> String {
        "aux_iers_gdr2_cross_id".to_string()
    }
}

#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, strum::Display)]
pub enum Col {
    iers_name,
    source_id,
}

impl Column for Col {}

#[cfg(test)]
pub fn collect_known(map: &mut std::collections::HashMap<String, Vec<String>>) {
    let mut col_strings = Vec::new();
    col_strings.push(Col::iers_name.to_string());
    col_strings.push(Col::source_id.to_string());
    map.insert(aux_iers_gdr2_cross_id.string(), col_strings);
}
